version: '3'

services:

  # Nginx Proxy
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.storage/conf.d:/etc/nginx/conf.d
      - ./.storage/vhost.d:/etc/nginx/vhost.d
      - ./.storage/html:/usr/share/nginx/html
      - ./.storage/dhparam:/etc/nginx/dhparam
      - ./.storage/certs:/etc/nginx/certs:ro

      - ./assets/nginx-custom-config.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./.storage/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # network_mode: bridge

  # MySQL
  # Point web servers to mysql for MySQL server
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.storage/mysql:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: always

  # MailHog
  # Point web servers to mailhog:1025 for SMTP Server
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
    expose:
      - 8025
    restart: always
    depends_on:
      - nginx_proxy
    environment:
      VIRTUAL_HOST: mailhog.${HOST_NAME}
      LETSENCRYPT_HOST: mailhog.${HOST_NAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 8025

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs: